AcUtils: AcUtils.AcDuration Class Reference
AcUtils.AcDuration Class Reference
Wrapper around TimeSpan so we can return our own formatted elapsed time string and still sort correctly in a grid based on the actual time span.
Public Member Functions
AcDuration (TimeSpan ts)
Constructor.
string ToString (string format, IFormatProvider provider)
The ToString implementation.
Equality comparison
bool Equals (AcDuration other)
IEquatable implementation to determine the equality of instances of type AcDuration.
override bool Equals (object other)
Overridden to determine equality.
override int GetHashCode ()
Override appropriate for type AcDuration.
Static Public Member Functions
static implicit operator TimeSpan (AcDuration rhs)
User-defined conversion from AcDuration to TimeSpan.
static implicit operator AcDuration (TimeSpan rhs)
User-defined conversion from TimeSpan to AcDuration.
Order comparison
int CompareTo (AcDuration other)
Generic IComparable implementation (default) for comparing AcDuration objects to sort by timespan.
int IComparable. CompareTo (object other)
Pre-generic interface implementation for code using reflection.
Detailed Description
Wrapper around TimeSpan so we can return our own formatted elapsed time string and still sort correctly in a grid based on the actual time span.
Definition at line 25 of file AcDuration.cs.
Constructor & Destructor Documentation
AcDuration()
AcUtils.AcDuration.AcDuration (TimeSpan ts) inline
Constructor.
Definition at line 32 of file AcDuration.cs.
Referenced by AcUtils.AcDuration.CompareTo(), and AcUtils.AcDuration.operator AcDuration().
Member Function Documentation
CompareTo() [1/2]
int AcUtils.AcDuration.CompareTo (AcDuration other) inline
Generic IComparable implementation (default) for comparing AcDuration objects to sort by timespan.
Parameters
other An AcDuration object to compare with this instance.
Returns
Value indicating the relative order of the AcDuration objects being compared.
Definition at line 99 of file AcDuration.cs.
Referenced by AcUtils.AcSession.CompareTo(), and AcUtils.AcDuration.CompareTo().
CompareTo() [2/2]
int IComparable. AcUtils.AcDuration.CompareTo (object other) inline private
Pre-generic interface implementation for code using reflection.
Parameters
other An AcDuration object to compare with this instance.
Returns
Return value of generic CompareTo(AcDuration) version.
Exceptions
ArgumentException thrown if argument is not an AcDuration object.
Definition at line 116 of file AcDuration.cs.
Equals() [1/2]
bool AcUtils.AcDuration.Equals (AcDuration other) inline
IEquatable implementation to determine the equality of instances of type AcDuration.
Parameters
other The AcDuration object being compared to this instance.
Returns
true if AcDuration other is the same, false otherwise.
Definition at line 61 of file AcDuration.cs.
Referenced by AcUtils.AcDuration.Equals().
Equals() [2/2]
override bool AcUtils.AcDuration.Equals (object other) inline
Overridden to determine equality.
Returns
Return value of generic Equals(AcDuration) version.
Definition at line 72 of file AcDuration.cs.
GetHashCode()
override int AcUtils.AcDuration.GetHashCode () inline
Override appropriate for type AcDuration.
Returns
Hash of our TimeSpan class data member.
Definition at line 84 of file AcDuration.cs.
operator AcDuration()
static implicit AcUtils.AcDuration.operator AcDuration (TimeSpan rhs) inline static
User-defined conversion from TimeSpan to AcDuration.
Definition at line 48 of file AcDuration.cs.
operator TimeSpan()
static implicit AcUtils.AcDuration.operator TimeSpan (AcDuration rhs) inline static
User-defined conversion from AcDuration to TimeSpan.
Definition at line 40 of file AcDuration.cs.
ToString()
string AcUtils.AcDuration.ToString (string format, IFormatProvider provider) inline
The ToString implementation.
Parameters
format The format specifier to use, e.g. Console.WriteLine(session.ToString("h"));
provider Allow clients to format output for their own types using ICustomFormatter.
Returns
The formatted string.
Exceptions
FormatException thrown if an invalid format string is specified.
Format specifiers:
G Show elapsed time in days, hours, minutes and seconds. Default when not using a format specifier.
H Hours.
M Minutes.
S Seconds.
D day or days.
Definition at line 140 of file AcDuration.cs.
Referenced by AcUtils.AcStopWatch.Stop().