AcUtils: AcUtils.Hist Class Reference
AcUtils.Hist Class Reference
The list of transactions from the hist command.
Static Public Member Functions
static void clear ()
Removes all elements from the (static) transaction history.
static bool init (string xml, bool EID=false, bool mergedOnly=false)
Populate this list with transactions from the XML emitted by the hist command.
Properties
static List< Transaction > Transactions [get, private set]
The list of Transaction objects.
Static Private Member Functions
static bool version (Transaction newTrans, XPathNavigator nav)
Converts the XML attributes of a single version element from the hist command to a Version object and then adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
static bool stream (Transaction newTrans, XPathNavigator nav)
Converts the XML attributes of a single stream element from the hist command to a Streams object and then adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
static bool comment (Transaction newTrans, XPathNavigator nav)
Converts the comment element for the transaction from the hist command and adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
static bool comp_rule (Transaction newTrans, XPathNavigator nav)
Converts the XML attributes of a single comp_rule element from the hist command and adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
static bool move (Transaction newTrans, XPathNavigator nav)
Converts the XML attributes of a single move element from the hist command to a Move object and then adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
Detailed Description
The list of transactions from the hist command.
try {
    AcResult result = await AcCommand.runAsync(@"hist -p ""NEPTUNE"" -t ""2013/10/25 14:01:40 - 2013/10/25 11:50:50"" -k promote -fevx");
    if (result == null || result.RetVal != 0) return false; // error occurred, check log file
    Hist.init(result.CmdResult); // populate list using XML from the hist command
    foreach (Transaction tran in Hist.Transactions.OrderBy(n => n))
    {
        Console.WriteLine(tran.ToString("LV"));
        List<AcUtils.Version> versions = tran.Versions; // get the versions in this transaction
        foreach (AcUtils.Version ver in versions.OrderBy(n => n))
            Console.WriteLine(ver.ToString("LV"));
        Console.WriteLine();
    }
}
catch (AcUtilsException ecx) {
    string msg = String.Format("AcUtilsException caught in Program.show{0}{1}", Environment.NewLine, ecx.Message);
    Console.WriteLine(msg);
}
catch (Exception ecx) {
    string msg = String.Format("Exception caught in Program.show{0}{1}", Environment.NewLine, ecx.Message);
    Console.WriteLine(msg);
}
Deprecated:
Prefer using LINQ to XML and custom query operators from the Extensions class.
Definition at line 909 of file Hist.cs.
Member Function Documentation
static void AcUtils.Hist.clear () inline static
Removes all elements from the (static) transaction history.
Definition at line 929 of file Hist.cs.
static bool AcUtils.Hist.comment (Transaction newTrans, XPathNavigator nav) inline static private
Converts the comment element for the transaction from the hist command and adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
Parameters
newTrans The transaction object being initialized.
nav Navigator object for querying the XML.
Returns
true if operation was successful, false otherwise.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<prog_name>-YYYY-MM-DD.log on failure to handle a range of exceptions.
Definition at line 1270 of file Hist.cs.
Referenced by AcUtils.Hist.init().
static bool AcUtils.Hist.comp_rule (Transaction newTrans, XPathNavigator nav) inline static private
Converts the XML attributes of a single comp_rule element from the hist command and adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
Parameters
newTrans The transaction object being initialized.
nav Navigator object for querying the XML.
Returns
true if operation was successful, false otherwise.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<prog_name>-YYYY-MM-DD.log on failure to handle a range of exceptions.
<?xml version="1.0" encoding="utf-8"?>
<AcResponse
    Command="hist"
    TaskId="27581">
  <transaction
      id="668"
      type="defcomp"
      time="1308596399"
      user="barnyrd">
    <stream
        name="PG_STAGE"
        streamNumber="7"
        depotName="PlayGround"
        type="normal"
        basis="PlayGround"
        basisStreamNumber="1"/>
    <version
        path="\.\Iconic"
        eid="288"
        virtual="1/1"
        real="46/1"
        virtualNamedVersion="PlayGround/1"
        realNamedVersion="IC_DEV1_barnyrd/1"
        elem_type="dir"
        dir="yes"/>
    <comp_rule
        kind="incl"
        xlinkStreamNum="45"
        xlinkStreamName="IC_DEV2"
        prevXlinkStreamNum="41"
        prevXlinkStreamName="IC_MAINT1"/>
  </transaction>
  <streams>
    <stream
        id="1"
        name="PlayGround"
        type="normal"/>
  </streams>
</AcResponse>
Definition at line 1357 of file Hist.cs.
Referenced by AcUtils.Hist.init().
static bool AcUtils.Hist.init (string xml, bool EID = false, bool mergedOnly = false) inline static
Populate this list with transactions from the XML emitted by the hist command.
Parameters
xml XML from the AccuRev hist command.
EID true if the hist command that generated xml included the -e (EID) command line option, otherwise false.
mergedOnly true to include only version elements that were the result of a merge operation, or false to include all.
Returns
true if parsing was successful, false otherwise.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<prog_name>-YYYY-MM-DD.log on failure to handle a range of exceptions.
Definition at line 962 of file Hist.cs.
static bool AcUtils.Hist.move (Transaction newTrans, XPathNavigator nav) inline static private
Converts the XML attributes of a single move element from the hist command to a Move object and then adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
Parameters
newTrans The transaction object being initialized.
nav Navigator object for querying the XML.
Returns
true if operation was successful, false otherwise.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<prog_name>-YYYY-MM-DD.log on failure to handle a range of exceptions.
Definition at line 1415 of file Hist.cs.
Referenced by AcUtils.Hist.init().
static bool AcUtils.Hist.stream (Transaction newTrans, XPathNavigator nav) inline static private
Converts the XML attributes of a single stream element from the hist command to a Streams object and then adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
Parameters
newTrans The transaction object being initialized.
nav Navigator object for querying the XML.
Returns
true if operation was successful, false otherwise.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<prog_name>-YYYY-MM-DD.log on failure to handle a range of exceptions.
Definition at line 1171 of file Hist.cs.
Referenced by AcUtils.Hist.init().
static bool AcUtils.Hist.version (Transaction newTrans, XPathNavigator nav) inline static private
Converts the XML attributes of a single version element from the hist command to a Version object and then adds it to the Transaction object being initialized. The Transaction object is added to our list of transactions if not already there, or updated if already present.
Parameters
newTrans The transaction object being initialized.
nav Navigator object for querying the XML.
Returns
true if operation was successful, false otherwise.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<prog_name>-YYYY-MM-DD.log on failure to handle a range of exceptions.
Definition at line 1067 of file Hist.cs.
Referenced by AcUtils.Hist.init().
Property Documentation
List<Transaction> AcUtils.Hist.Transactions static get private set
The list of Transaction objects.
Definition at line 921 of file Hist.cs.