AcUtils: AcUtils.AcDebug Class Reference
AcUtils.AcDebug Class Reference
Use to log and display error and general purpose text messages, and to save the XML param data sent by AccuRev to a trigger for development, debugging, and troubleshooting purposes. For OS environment problems, log the system network activity generated by the program by modifying <prog_name>.exe.config similar to this version.
Static Public Member Functions
static bool paramFileCopy (string xmlFile, ParamFileCopy pfcopy, string trigger, string prncpl, string command)
Used by a trigger to save the content of the XML param file passed to it by AccuRev to %LOCALAPPDATA%\AcTools\Param\<trigger-command-principal-timestamp>.xml.
static bool paramFileCopy (ParamFileCopy pfcopy, string xml, string trigger, string prncpl)
Used by the server_auth_trig to save the content of the XML param data passed to it by AccuRev to %LOCALAPPDATA%\AcTools\Param\server_auth_trig-principal-timestamp.xml.
static void Log (string message, bool formatting=true)
Write the message text to STDOUT, to weekly log files located in %LOCALAPPDATA%\AcTools\Logs, and to trigger.log in the AccuRev server's ..storage\site_slice\logs folder in the case of triggers.
static void Log (string message, string xmlParamFile, bool formatting=true)
Used by triggers, this method overload includes all functionality of Log(string, bool) and adds overwriting the trigger's xmlParamFile with the message text so it is displayed in the console or error dialog given to the user on trigger failure.
static bool initAcLogging ()
Initialize application logging support, for general purpose or error messages, in conjunction with a client application's <prog_name>.exe.config file and Log(string, bool).
static string getLogFile ()
Get the log file full path name.
static void unhandledException (object sender, UnhandledExceptionEventArgs args)
Ensure that an unhandled exception gets logged to %LOCALAPPDATA%\AcTools\Logs\<prog_name>-YYYY-MM-DD.log before the system default handler terminates the application.
static void errorDataHandler (object sendingProcess, DataReceivedEventArgs errLine)
Centralized error handler.
Properties
static string TrigTargetEnv [get]
Returns "AccuRevTriggers", the name of the environment variable on the AccuRev server that points to the network share where TriggersTarget.xml and other application support files are located.
Static Private Member Functions
static void createParamFile (string fileName, string content)
Helper function that creates the XML param data copy.
static string getStamp ()
Helper function for creating a unique filename for our copy of the XML param data.
static bool entryInTrigTargetsFile (string trigger, string prncpl)
Determine if an entry exists for this user and trigger combo in TriggersTarget.xml.
Detailed Description
Use to log and display error and general purpose text messages, and to save the XML param data sent by AccuRev to a trigger for development, debugging, and troubleshooting purposes. For OS environment problems, log the system network activity generated by the program by modifying <prog_name>.exe.config similar to this version.
Definition at line 100 of file AcDebug.cs.
Member Function Documentation
static void AcUtils.AcDebug.createParamFile (string fileName, string content) inline static private
Helper function that creates the XML param data copy.
Parameters
fileName Name of file to create.
content String containing the XML param data.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<trig_name>-YYYY-MM-DD.log on failure to handle a range of exceptions.
Definition at line 252 of file AcDebug.cs.
Referenced by AcUtils.AcDebug.paramFileCopy().
static bool AcUtils.AcDebug.entryInTrigTargetsFile (string trigger, string prncpl) inline static private
Determine if an entry exists for this user and trigger combo in TriggersTarget.xml.
Use the CopyParmFileTrigTarget enum directive in the appSettings section of a <trigger>.exe.config file (located in the same folder as the trigger's executable) to have the trigger's XML param data copied to %LOCALAPPDATA%\AcTools\Param\<trigger-command-principal-timestamp>.xml for specific users and triggers. Only param data for matching entries in TriggersTarget.xml located on the AccuRevTriggers network share are copied.
Parameters
trigger The name of the trigger sent by AccuRev.
prncpl Name of the principal sent by AccuRev.
Returns
true if entry exists, false otherwise.
Exceptions
XPathException caught and logged in %LOCALAPPDATA%\AcTools\Logs\<trig_name>-YYYY-MM-DD.log on xpath failure.
Exception caught and logged in same on failure to handle a range of exceptions.
In <trigger>.exe.config:
<appSettings>
...
<add key="ParamFileCopy" value="CopyParmFileTrigTarget" />
</appSettings>
Example TriggersTarget.xml:
<Triggers>
  <Trigger Name="server-post-promote">
    <Principal Name="barnyrd"></Principal>
  </Trigger>
  <Trigger Name="server_admin_trig">
    <Principal Name="robert"></Principal>
    <Principal Name="barnyrd"></Principal>
  </Trigger>
  <Trigger Name="server_preop_trig">
    <Principal Name="thomas"></Principal>
  </Trigger>
  <Trigger Name="server_auth_trig">
    <Principal Name="madhuri"></Principal>
    <Principal Name="thomas"></Principal>
  </Trigger>
</Triggers>
Definition at line 336 of file AcDebug.cs.
Referenced by AcUtils.AcDebug.paramFileCopy().
static void AcUtils.AcDebug.errorDataHandler (object sendingProcess, DataReceivedEventArgs errLine) inline static
Centralized error handler.
Parameters
sendingProcess The spawned process.
errLine The error message sent to this method by the spawned process.
Definition at line 562 of file AcDebug.cs.
Referenced by AcUtils.AcGroups.isMember().
static string AcUtils.AcDebug.getLogFile () inline static
Get the log file full path name.
Returns
Full path to the log file if it exists, otherwise null.
Definition at line 536 of file AcDebug.cs.
static string AcUtils.AcDebug.getStamp () inline static private
Helper function for creating a unique filename for our copy of the XML param data.
Returns
String to ensure the copied file is unique and doesn't get subsequently overwritten.
Definition at line 285 of file AcDebug.cs.
Referenced by AcUtils.AcDebug.paramFileCopy().
static bool AcUtils.AcDebug.initAcLogging () inline static
Initialize application logging support, for general purpose or error messages, in conjunction with a client application's <prog_name>.exe.config file and Log(string, bool).
Creates weekly log files in %LOCALAPPDATA%\AcTools\Logs in the format <prog_name>-YYYY-MM-DD.log with the first day of the current week in the file name. The AcTools\Logs folder is created if not already there. Log files can grow to a maximum of 80MB in size. At least 2.3GB free space must exist for logging to continue. Additional log files are created with an iteration part (blue circle) should a write conflict occur:
Returns
true if logging support successfully initialized, false on error.
Exceptions
Exception caught on failure to handle a range of exceptions with error sent to STDOUT.
Example usage:
// Init our logging support so we can log errors.
string error;
if (!AcDebug.initAcLogging())
{
    MessageBox.Show(error, "PromoHist", MessageBoxButtons.OK, MessageBoxIcon.Stop);
    return;
}
XML that must exist in <prog_name>.exe.config. Change source name attribute to <prog_name>.
<system.diagnostics>
  <assert assertuienabled="false"/>
  <sources>
    <source name="PromoHist">  <!-- name attribute value must be program executable's root name -->
      <listeners>
        <remove name="Default" />
        <add name="AcLog" type="Microsoft.VisualBasic.Logging.FileLogTraceListener, Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" />
      </listeners>
    </source>
  </sources>
</system.diagnostics>
Definition at line 483 of file AcDebug.cs.
static void AcUtils.AcDebug.Log (string message, bool formatting = true) inline static
Write the message text to STDOUT, to weekly log files located in %LOCALAPPDATA%\AcTools\Logs, and to trigger.log in the AccuRev server's ..storage\site_slice\logs folder in the case of triggers.
Parameters
message The text to be logged.
formatting true to include the date, time and newline formatting in the log file. false for no formatting.
See also
Log(string, string, bool)
Definition at line 385 of file AcDebug.cs.
Referenced by AcUtils.AcCommand.AcCommand(), AcUtils.AcDateTime.AcDate2DateTime(), AcUtils.Hist.comment(), AcUtils.Hist.comp_rule(), AcUtils.AcDebug.createParamFile(), AcUtils.AcDebug.entryInTrigTargetsFile(), AcUtils.AcDebug.errorDataHandler(), AcUtils.AcQuery.getAccuRevVersionAsync(), AcUtils.AcQuery.getAcGUIpath(), AcUtils.AcPreferences.getAcHomeFolderAsync(), AcUtils.AcQuery.getElementNameAsync(), AcUtils.AcDepot.getHierarchyAsync(), AcUtils.AcQuery.getPrincipalAsync(), AcUtils.AcWorkspaces.getReferenceTreesXMLAsync(), AcUtils.AcQuery.getServerFromAcClientCnf(), AcUtils.AcPreferences.getUseIgnoreElemsOptimizationAsync(), AcUtils.AcWorkspaces.getWorkspacesXMLAsync(), AcUtils.Stat.init(), AcUtils.Hist.init(), AcUtils.AcGroups.initAsync(), AcUtils.AcDepot.initAsync(), AcUtils.AcSessions.initAsync(), AcUtils.AcProperties.initAsync(), AcUtils.AcLocks.initAsync(), AcUtils.AcPermissions.initAsync(), AcUtils.AcStreams.initAsync(), AcUtils.AcUsers.initAsync(), AcUtils.AcDepots.initAsync(), AcUtils.AcUser.initFromADAsync(), AcUtils.AcUser.initGroupsListAsync(), AcUtils.AcGroups.initMembersListAsync(), AcUtils.AcGroups.isMember(), AcUtils.AcDepot.listFile(), AcUtils.AcLocks.lockAsync(), AcUtils.AcDebug.Log(), AcUtils.Hist.move(), AcUtils.AcDebug.paramFileCopy(), AcUtils.AcCommand.run(), AcUtils.AcCommand.runAsync(), AcUtils.AcRules.runCmdAsync(), AcUtils.AcLocks.runCommand(), AcUtils.AcWorkspaces.storeWSpaces(), AcUtils.Hist.stream(), AcUtils.AcDebug.unhandledException(), AcUtils.AcLocks.unlockAsync(), and AcUtils.Hist.version().
static void AcUtils.AcDebug.Log (string message, string xmlParamFile, bool formatting = true) inline static
Used by triggers, this method overload includes all functionality of Log(string, bool) and adds overwriting the trigger's xmlParamFile with the message text so it is displayed in the console or error dialog given to the user on trigger failure.
Results from AccuRev commands issued on the command line are sent to STDOUT for both success and failure. For the AccuRev GUI, results are discarded if the program return value is zero (0) (Success). For triggers that return a non-zero program return value (Failure), the message text will display in the console or error dialog provided the xmlParamFile sent by AccuRev was overwritten with it. Otherwise, the raw XML param data will display which is not user-friendly.
Parameters
message The text to be logged and displayed to the user on trigger failure.
xmlParamFile The XML trigger param file sent by AccuRev to the trigger.
formatting true to include the date, time and newline formatting in the log file. false for no formatting.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<trig_name>-YYYY-MM-DD.log on failure to overwrite the XML param file.
See also
AcUtils.ParamFileCopy
Definition at line 423 of file AcDebug.cs.
static bool AcUtils.AcDebug.paramFileCopy (string xmlFile, ParamFileCopy pfcopy, string trigger, string prncpl, string command) inline static
Used by a trigger to save the content of the XML param file passed to it by AccuRev to %LOCALAPPDATA%\AcTools\Param\<trigger-command-principal-timestamp>.xml.
Parameters
xmlFile XML param file sent to the trigger by AccuRev.
pfcopy ParamFileCopy enum to indicate in what manner to handle the XML param file passed by AccuRev.
trigger Name of this trigger.
prncpl Principal name of the user who issued the command.
command AccuRev command issued.
Returns
true if operation ran successfully, false on error.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\<trig_name>-YYYY-MM-DD.log on failure to handle a range of exceptions.
See also
paramFileCopy(ParamFileCopy, string, string, string)
Definition at line 131 of file AcDebug.cs.
static bool AcUtils.AcDebug.paramFileCopy (ParamFileCopy pfcopy, string xml, string trigger, string prncpl) inline static
Used by the server_auth_trig to save the content of the XML param data passed to it by AccuRev to %LOCALAPPDATA%\AcTools\Param\server_auth_trig-principal-timestamp.xml.
Overloaded version used by the server_auth_trig since the XML param data is sent, for security reasons, via STDIN and not in a file.
Parameters
pfcopy ParamFileCopy enum to indicate in what manner to handle the XML param data passed by AccuRev.
xml String containing the XML param data.
trigger Name of the trigger (server_auth_trig until something changes).
prncpl Principal name of the user who issued the command.
Returns
true if operation ran successfully, false on error.
Exceptions
Exception caught and logged in %LOCALAPPDATA%\AcTools\Logs\server_auth_trig-YYYY-MM-DD.log on failure to handle a range of exceptions.
See also
paramFileCopy(string, ParamFileCopy, string, string, string)
Definition at line 202 of file AcDebug.cs.
static void AcUtils.AcDebug.unhandledException (object sender, UnhandledExceptionEventArgs args) inline static
Ensure that an unhandled exception gets logged to %LOCALAPPDATA%\AcTools\Logs\<prog_name>-YYYY-MM-DD.log before the system default handler terminates the application.
// save an unhandled exception in log file before program terminates
AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(AcDebug.unhandledException);
See also
AppDomain.UnhandledException Event
Definition at line 551 of file AcDebug.cs.
Property Documentation
string AcUtils.AcDebug.TrigTargetEnv static get
Returns "AccuRevTriggers", the name of the environment variable on the AccuRev server that points to the network share where TriggersTarget.xml and other application support files are located.
Definition at line 109 of file AcDebug.cs.