AcUtils: AcUtils.AcDuration Struct Reference
AcUtils.AcDuration Struct Reference
Wrapper around TimeSpan so we can return our own formatted elapsed time string and still sort correctly in a grid based on the actual time span.
Public Member Functions
AcDuration (TimeSpan ts)
Constructor.
int CompareTo (AcDuration rhs)
Used by the grid to order our AcDuration objects.
override string ToString ()
Formatted string to show elapsed time in days, hours, minutes and seconds.
Static Public Member Functions
static implicit operator TimeSpan (AcDuration rhs)
User-defined conversion from AcDuration to TimeSpan.
static implicit operator AcDuration (TimeSpan rhs)
User-defined conversion from TimeSpan to AcDuration.
Detailed Description
Wrapper around TimeSpan so we can return our own formatted elapsed time string and still sort correctly in a grid based on the actual time span.
Definition at line 25 of file AcDuration.cs.
Constructor & Destructor Documentation
AcUtils.AcDuration.AcDuration (TimeSpan ts) inline
Constructor.
Definition at line 32 of file AcDuration.cs.
Referenced by AcUtils.AcDuration.operator AcDuration().
Member Function Documentation
int AcUtils.AcDuration.CompareTo (AcDuration rhs) inline
Used by the grid to order our AcDuration objects.
Definition at line 56 of file AcDuration.cs.
Referenced by AcUtils.AcSession.CompareTo().
static implicit AcUtils.AcDuration.operator AcDuration (TimeSpan rhs) inline static
User-defined conversion from TimeSpan to AcDuration.
Definition at line 48 of file AcDuration.cs.
static implicit AcUtils.AcDuration.operator TimeSpan (AcDuration rhs) inline static
User-defined conversion from AcDuration to TimeSpan.
Definition at line 40 of file AcDuration.cs.
override string AcUtils.AcDuration.ToString () inline
Formatted string to show elapsed time in days, hours, minutes and seconds.
Definition at line 69 of file AcDuration.cs.
Referenced by AcUtils.AcStopWatch.Stop().